### ISSUE TITLE
Snapdragon::VislamManager::GetPose

### ISSUE THREAD

**Issue by PopeyedLocket** [ATLFlight/ros-examples#2]
Should this line have `timestamp_ns` as a reference?:
`int32_t Snapdragon::VislamManager::GetPose( mvVISLAMPose& pose, int64_t& pose_frame_id, uint64_t timestamp_ns )`

Else, timestamp is not set for the `/vislam/pose` message.

**Comment by rkintada** [comment]
Yes.  This is a bug.  Thanks for pointing this out. I will push a fix soon.

**Comment by rkintada** [comment]
I Just pushed a fix for this issue.

thanks
Rama.
