### ISSUE TITLE
test_snap_cam_manager "fails"

### ISSUE THREAD

**Issue by Seanmatthews** [ATLFlight/ros-examples#4]
On `rosrun snap_ros_examples test_snap_cam_manager`:

> The apps <--> dsp offset = [1491187394706895998 ](ns) Apps ClockType[CLOCK_REALTIME]
> [2459383510] VISLAM INFO: FindCamera 65: Camera of type 1 has ID = 0
> [KPI Perf  836204953] openCamera: E PROFILE_OPEN_CAMERA camera id 0
> [2459534886] VISLAM INFO: Initialize 89: Opened camera 0 Type: 1
> [2459536920] VISLAM INFO: Initialize 116: Setting FPS to 30
> MachineVision SDK is licensed as community user
> LNX_8074 supported? 1
> LNX_8096 supported? 0
> LNX_IA64 supported? 0
> WINDOWS supported? 0
> FASTCV: fcvAvailableHardware Linux
> FASTCV: fcvAvailableHardware Linux
> PASS: CameraManager::Initialize()
> PASS: CameraManager::Start()
> Latest FrameId: -1 Image Size: 460800 Fps: 0 Expsure: 3479.99 Oldest FrameId: -1
> Latest FrameId: -1 Image Size: 460800 Fps: 0 Expsure: 3479.99 Oldest FrameId: -1
> Latest FrameId: -1 Image Size: 460800 Fps: 0 Expsure: 3479.99 Oldest FrameId: -1
> Latest FrameId: -1 Image Size: 460800 Fps: 0 Expsure: 3479.99 Oldest FrameId: -1
> Latest FrameId: -1 Image Size: 460800 Fps: 0 Expsure: 3479.99 Oldest FrameId: -1
> PASS: Getting Frames From OPTIC_FLOW Camera

The lack of FrameId causes the VISLAM example to not work because the camera manager never starts. Also referencing [this issue](https://github.com/ATLFlight/ATLFlightDocs/issues/21), in case it has something to do with it.

**Comment by rkintada** [comment]
This related to the Camera Issue & fix described here https://developer.qualcomm.com/forum/qdn-forums/hardware/snapdragon-flight/34157

Can you please try this and let me know if this addresses the issue? 
Thanks
Rama.

**Comment by Seanmatthews** [comment]
Yup. Had been fixed after Qualcomm released the non-broken camera drivers. Closing.
