### ISSUE TITLE
Which flight software is used to flight test?

### ISSUE THREAD

**Issue by Seanmatthews** [ATLFlight/ros-examples#8]
@rkintada I'm curious which flight controller you use to test this repo in flight with the Snapdragon Flight? Do you use PX4 or some other? Do you use additional sensors? Some prescribed usage in the README might benefit user.

**Comment by rkintada** [comment]
@Seanmatthews for the basic testing we use the bench-testing with hand-motions.  This is also tested with Qualcomm's Snapdragon Navigator Flight Controller( the flight controller is in the process of being released on Qualcomm Developer Network soon ) with a recommendation of the Flight Platform.   The sensors are pretty standard ones we use( IMU(MPU9x50), Pressure Sensor(BMP280), Optic Flow- OV7251( not when using VISLAM), external GPS).
